### PR TITLE
ENH: make tools/rec_asciinema usable by others, add color to the path in the prompt

### PR DESCRIPTION
**Pull request by yarikoptic**
- added coloring to the path, so it is easier to see the boundaries of the commands execution
- I have neither `/demo`, nor `~/datalad` repository.  `datalad` command is just available (virtualenv).

### CODE REVIEW

**Comment by yarikoptic** [comment]
attn @aqw
In d20def8e462017bd7fc35a251192fa5bc05381b6  added creating an additional file: .cmds which is just a list of commands which were ran and how long it took (left in the same line in the '# comment')

asciinemas are cool BUT for impatient ones would be cool if we could provide "expandable" "command history" which would just list all the commands so they could get immediate preview of what this asciinema "talks" about.  Timings would also be useful to give some kind of an idea on how long it would take to run this command.

here is an example:
```shell
$> cat docs/casts/dummy.sh                                                              
say "nothing"
run "ls"
say "something"
run "sleep 0"
run "sleep 1"
run "sleep 2"
run "sleep 3"
run "ls"
run "datalad --help"

$> cat dummy.cmds         
ls     # 0.075 sec
sleep 0     # 0.085 sec
sleep 1     # 1.041 sec
sleep 2     # 2.072 sec
sleep 3     # 3.040 sec
ls     # 0.072 sec
datalad --help     # 1.147 sec
```

please consider adopting the changes ;)

edit1: force pushed a change to print elapsed time only to two digits after . since precision is defined by the loop waiting 10 ms before pulling

**Comment by yarikoptic** [comment]
although probably that last commit could just be a separate `cast2commands` script... duplication of a run, but clearer.

**Comment by yarikoptic** [comment]
ok -- pushed extended version (generated by my patched version in the PR to you). https://asciinema.org/a/oryzxsEREFPfnRG53oA5evz4A  and the .cmds dump is http://www.onerussian.com/tmp/heudiconv_dicom_to_bids.cmds

**Comment by aqw** [comment]
@yarikoptic I am not a screencast person at all. IMO, the standard should be to provide a transcript with all command and comments, formatted in the page.

The only glitch with that, is keeping the page in sync with any screencast changes. :-/

---Alex

**Comment by yarikoptic** [comment]
full transcript would indeed be good to have, but it might be quite bloated.  In many cases it is nice to see (and be able to cut paste) just the commands which were ran.  But, I guess, range of opportunities is large ;)

**Comment by mih** [comment]
BTW: there is tools/cast2script which provides an actual script

**Pull request merged**
